theme: jekyll-theme-slate

title: "Supernatural"
description: "Bienvenue sur mon site dédié à la série Supernatural !"
nav:
  - title: "Home"
    url: /
  - title: "Personnages principaux"
    url: /characters/Perso
  - title: "Bestiaire"
    url: /bestiaire/bestiaire 
 
