theme: jekyll-theme-slate

title: "Supernatural"
description: "Bienvenue dans mon blog dédié à la serie Supernatural !"
nav:
  - title: "Home"
    url: /
  - title: "Les personnages principaux"
    url: /characters/Perso.md
  - title: "Bestiaire"
    url: /Bestiaire/bestiaire.md 
